### PR TITLE
Adds sample for a SPIRE quickstart

### PR DESCRIPTION
**Pull request by alexandrealvino**
**Please provide a description of this PR:**

Adds a sample for Spire integration quick-start under samples/security/spire

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by jufantozzi** [comment]
Just remembered this, but  shouldn't we be signing every commit? I think this is a requirement for merging with upstream (I also need to sign my own commits as I forgot 😛 )

**Comment by maxlambrecht** [comment]
> Just remembered this, but shouldn't we be signing every commit? I think this is a requirement for merging with upstream (I also need to sign my own commits as I forgot 😛 )

Yes, the commits should be signed, a commit can be amended this way:

```
git commit --amend --no-edit -S
```

**Review by maxlambrecht — APPROVED** [review]
💯

**Review by mchurichi — APPROVED** [review]
LGTM!

**Pull request closed without merging**
